export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ALL_BOXES_REQUEST = "ALL_BOXES_REQUEST";
export const ALL_BOXES_SUCCESS = "ALL_BOXES_SUCCESS";
export const ALL_BOXES_FAIL = "ALL_BOXES_FAIL";

export const DELETE_BOX_REQUEST = "DELETE_BOX_REQUEST";
export const DELETE_BOX_SUCCESS = "DELETE_BOX_SUCCESS";
export const DELETE_BOX_FAIL = "DELETE_BOX_FAIL";
export const DELETE_BOX_RESET = "DELETE_BOX_RESET";

export const UPDATE_BOX_REQUEST = "UPDATE_BOX_REQUEST";
export const UPDATE_BOX_SUCCESS = "UPDATE_BOX_SUCCESS";
export const UPDATE_BOX_FAIL = "UPDATE_BOX_FAIL";
export const UPDATE_BOX_RESET = "UPDATE_BOX_RESET";

export const BOX_DETAILS_REQUEST = "BOX_DETAILS_REQUEST";
export const BOX_DETAILS_SUCCESS = "BOX_DETAILS_SUCCESS";
export const BOX_DETAILS_FAIL = "BOX_DETAILS_FAIL";

export const NEW_BOX_REQUEST = "NEW_BOX_REQUEST";
export const NEW_BOX_SUCCESS = "NEW_BOX_SUCCESS";
export const NEW_BOX_FAIL = "NEW_BOX_FAIL";
export const NEW_BOX_RESET = "NEW_BOX_RESET";